add buffer cache on ANRTracing to capture hard stall.
meitu/MTHawkeye pull request #29
Opened 2019-07-10 10:46 UTC by euanchan

增加跟踪卡死的记录

- 新增 MTHANRTracingBufferRunner 用于记录最近发生的 Runloop Activities, AppLifeActivities 及卡顿发生时主线程采样的调用栈
- 下次启动时，如果读取到 App 未正常退出( AppLife Activities），可读取最后采样到的调用栈的时间点，和最后记录到的 Runloop Activity 时间点，如果为卡死状态被杀，会有个时间差。这个时间差即为卡死的时间，这段区间内 `MTHANRDetectThread` 定时采样到的主线程堆栈，即为卡死期间主线程在做的事。
- 增加对应的 UI 展示视图，卡死发生后，下一次进入应用。进入到 `Hawkeye ANR Records` 界面，即可看到卡死的记录。

 @panmingyang2009 @hello-david

2019-07-12 09:58 UTC, euanchan commented
在部分机器上测试发现后进入后台后，对 suspend 引起的 runloop 事件回调处理仍有问题。现象表现为：

```
// 将 App 切换到后台

[hawkeye] 49:27:135 [Info] ANR suspended runloop fix, start 1562924962.125513
[hawkeye] 49:27:135 [Info] ANR suspended runloop fix, diff: 5009.238ms, curTime: 1562924967.135  (这里在 didEnterBackground 通知里执行了一个 5 秒左右的 main queue 后台任务)
[hawkeye] 49:27:135 [Info] beforeTimers
[hawkeye] 49:27:135 [Info] ANR suspended runloop fix, diff: 0.020ms, curTime: 1562924967.135
[hawkeye] 49:27:135 [Info] beforeSources
[hawkeye] 49:27:135 [Info] ANR suspended runloop fix, diff: 0.046ms, curTime: 1562924967.135
[hawkeye] 49:27:135 [Info] beforeTimers
[hawkeye] 49:27:135 [Info] ANR suspended runloop fix, diff: 0.017ms, curTime: 1562924967.135
[hawkeye] 49:27:135 [Info] beforeSources
[hawkeye] 49:27:137 [Info] ANR suspended runloop fix, diff: 1.961ms, curTime: 1562924967.137
[hawkeye] 49:27:137 [Info] beforeTimers
[hawkeye] 49:27:137 [Info] ANR suspended runloop fix, diff: 0.047ms, curTime: 1562924967.137
[hawkeye] 49:27:137 [Info] beforeSources
[hawkeye] 49:27:137 [Info] ANR suspended runloop fix, diff: 0.044ms, curTime: 1562924967.137
[hawkeye] 49:27:137 [Info] beforeTimers
[hawkeye] 49:27:137 [Info] ANR suspended runloop fix, diff: 0.016ms, curTime: 1562924967.137
[hawkeye] 49:27:137 [Info] beforeSources
[hawkeye] 49:27:137 [Info] ANR suspended runloop fix, diff: 0.022ms, curTime: 1562924967.137
[hawkeye] 49:27:137 [Info] beforeTimers
[hawkeye] 49:27:138 [Info] ANR suspended runloop fix, diff: 0.546ms, curTime: 1562924967.137
[hawkeye] 49:27:138 [Info] beforeSources

// App suspending.

[hawkeye] 49:44:134 [Info] ANR suspended runloop fix, reset
[hawkeye] 49:44:134 [Info] beforeWaiting
[hawkeye] 49:44:134 [Info] afterWaiting

--- ANR event: ---
time: 1562924962.125513
duration: 22.00831699371338s
snapshots: (6)
   1562924962.580957:
   1562924964.198177:
   1562924964.302932:
   1562924965.917392:
   1562924966.02276:
```

这是无法通过 diff 来判断，是否从 suspend 中恢复。

一个参考的方法是如果是后台时期发生的 runloop timeout，则需要结合 snapsshots 来计算实际的主线程卡住耗时。

2019-07-15 03:45 UTC, euanchan commented
> 在部分机器上测试发现后进入后台后，对 suspend 引起的 runloop 事件回调处理仍有问题。现象表现为：
> 
> ```
> ...
> // 将 App 切换到后台
> 
> [hawkeye] 49:27:135 [Info] ANR suspended runloop fix, start 1562924962.125513
> [hawkeye] 49:27:135 [Info] ANR suspended runloop fix, diff: 5009.238ms, curTime: 1562924967.135  (这里在 didEnterBackground 通知里执行了一个 5 秒左右的 main queue 后台任务)
> [hawkeye] 49:27:135 [Info] beforeTimers
> [hawkeye] 49:27:135 [Info] ANR suspended runloop fix, diff: 0.020ms, curTime: 1562924967.135
> [hawkeye] 49:27:135 [Info] beforeSources
> [hawkeye] 49:27:135 [Info] ANR suspended runloop fix, diff: 0.046ms, curTime: 1562924967.135
> [hawkeye] 49:27:135 [Info] beforeTimers
> [hawkeye] 49:27:135 [Info] ANR suspended runloop fix, diff: 0.017ms, curTime: 1562924967.135
> [hawkeye] 49:27:135 [Info] beforeSources
> [hawkeye] 49:27:137 [Info] ANR suspended runloop fix, diff: 1.961ms, curTime: 1562924967.137
> [hawkeye] 49:27:137 [Info] beforeTimers
> [hawkeye] 49:27:137 [Info] ANR suspended runloop fix, diff: 0.047ms, curTime: 1562924967.137
> [hawkeye] 49:27:137 [Info] beforeSources
> [hawkeye] 49:27:137 [Info] ANR suspended runloop fix, diff: 0.044ms, curTime: 1562924967.137
> [hawkeye] 49:27:137 [Info] beforeTimers
> [hawkeye] 49:27:137 [Info] ANR suspended runloop fix, diff: 0.016ms, curTime: 1562924967.137
> [hawkeye] 49:27:137 [Info] beforeSources
> [hawkeye] 49:27:137 [Info] ANR suspended runloop fix, diff: 0.022ms, curTime: 1562924967.137
> [hawkeye] 49:27:137 [Info] beforeTimers
> [hawkeye] 49:27:138 [Info] ANR suspended runloop fix, diff: 0.546ms, curTime: 1562924967.137
> [hawkeye] 49:27:138 [Info] beforeSources
> 
> // App suspending.
> 
> // 将 App 切回前台
> 
> [hawkeye] 49:44:134 [Info] ANR suspended runloop fix, reset
> [hawkeye] 49:44:134 [Info] beforeWaiting
> [hawkeye] 49:44:134 [Info] afterWaiting
> 
> --- ANR event: ---
> time: 1562924962.125513
> duration: 22.00831699371338s
> snapshots: (6)
>    1562924962.580957:
>    1562924964.198177:
>    1562924964.302932:
>    1562924965.917392:
>    1562924966.02276:
> ```
> 
> 这是无法通过 diff 来判断，是否从 suspend 中恢复。
> 
> 一个参考的方法是如果是后台时期发生的 runloop timeout，则需要结合 snapsshots 来计算实际的主线程卡住耗时。

ed77aa906a09ddd9540ae23db3ce1dd333e7c99b 已做了调整

2019-07-17 06:07 UTC, hello-david requested changes
经过测试
1.后台卡顿处理异常已修复。
2.新增卡死异常处理流程正常。

2019-07-17 06:12 UTC, hello-david approved these changes

2019-07-17 06:35 UTC, merged